imentore-cms/config/routes.rb
Imentore::Core::Engine.routes.draw do
  namespace :admin do
    # resources :asset_folders do
    #   resources :assets
    # end
    resources :pages
    resources :notices
    resources :themes do
      resources :asset_folders, except:[:show] do
        get "new/:parent_id", to: "asset_folders#new",   via: "get", as: "new_folder", :on => :collection
        resources :assets
      end
      resources :templates do
        get 'layouts', :on => :collection, to: 'templates#layouts', as: 'layouts'
        get 'view_default', 'copy_default', :on => :member
      end
    end
  end
end

imentore-cms/app/models/imentore/theme.rb
module Imentore
  class Theme < ActiveRecord::Base
    belongs_to :store
    belongs_to :manager_theme, :class_name => Imentore::Manager::Theme, :foreign_key => "admin_imentore_theme_id"
    
    has_many :folders, :class_name => Imentore::AssetFolder, :foreign_key => "theme_id", :dependent => :destroy
    has_many :templates, class_name: Imentore::Template, :dependent => :destroy
    has_many :assets, through: :folders, source: :assets


    scope :theme_system, -> { where(system: true) }
    # scope :default, where(default: true)

    def default_layout
      layout_name = templates.find_by_default(true).try(:path)
      layout_name ||= templates.find_by_path('layouts/#{name}".downcase').try(:path)
    end
  end
end

imentore-cms/app/controllers/imentore/admin/themes_controller.rb
module Imentore
  module Admin
    class ThemesController < Admin::BaseController
      inherit_resources
      respond_to :js, :json, :html

      before_action :uniqueness_active, only:[:update, :create]


      def create
        create! { layouts_admin_theme_templates_path(@theme) }
      end

      def update
        update! do |success, failure|
          success.html{ redirect_to admin_themes_path }
          success.json { render json: { message: "success", html: @html}, :status => 200 }
          success.js { @themes = collection }
          failure.html{ render :show }
        end
      end

      def destroy
        destroy! { admin_themes_path }
      end
      
      protected

      def theme_params
        params.require(:theme).permit(:active, :name)
      end

      def uniqueness_active
        if params[:theme][:active] == '1'
          # current_store.themes.updates_all(active: false)
          current_store.themes.find_by_active(true).update_attribute(:active, false) if current_store.themes.find_by_active(true)
        end
      end

      def begin_of_association_chain
        current_store
      end
    end
  end
end

imentore-cms/app/views/imentore/admin/themes/_index.html.slim
- model_class = Imentore::Theme

.row
  .col-lg-12
    .ibox.float-e-margins
      .ibox-title
        h5=t model_class.model_name.human.pluralize, scope: 'activerecord.models'.titleize
        / h5= t(:product_index)
        .ibox-tools
          a.collapse-link
            i.fa.fa-chevron-up
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            i.fa.fa-wrench
          ul.dropdown-menu.dropdown-user
            / li
            /   a href="#"  Config option 1
            / li
            /   a href="#"  Config option 2
          a.close-link
            i.fa.fa-times
      .ibox-content
        .table-responsive
          table.table.table.table-striped.table-hover.table-condensed.table-bordered
            thead
              tr
                th= model_class.human_attribute_name(:status)
                / th= model_class.human_attribute_name(:user_for)
                th= model_class.human_attribute_name(:name)
                th= model_class.human_attribute_name(:actions)
            tbody
              - @themes.each do |theme|
                tr
                  td
                    = check_box_tag 'i-check-invoice', 1, theme.active, class: 'i-checks', :data => { :remote => true, :url => admin_theme_path(theme, theme:{active:'1'}) }, disabled: theme.active
                  / td= t theme.manager_theme.used_for unless theme.manager_theme.nil?
                  td= theme.name
                  td
                    = link_to layouts_admin_theme_templates_path(theme), :class => 'btn btn-outline btn-default btn-sm', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
                      i.icon-black.icon-edit
                      '
                      = t(:edit)
                    / = link_to(admin_theme_path(theme), class: 'btn') do
                    /   i.icon-black.icon-edit
                    /   '
                    '
                    - if theme.manager_theme.nil?
                      = link_to admin_theme_path(theme), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-outline btn-danger btn-sm', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
                        i.icon-white.icon-trash
                        '
                        = t(:remove)
        .row 
          .hr-line-dashed
          .form-group
            .col-sm-4.col-sm-offset-1
              = link_to(new_admin_theme_path, :class=>'btn btn-primary') do
                i.fa.fa-plus
                '

                = I18n.t(:new, scope: 'helpers.submit', model: model_class.model_name.human)

css:
  .icheckbox_square-green.checked.disabled {
    background-position: -48px!important;
    }

javascript:
  $(document).ready(function(){
    $('.i-checks').iCheck({
      checkboxClass: 'icheckbox_square-green',
      radioClass: 'iradio_square-green',
    });
    $('input').on('ifChecked', function(event){
      var url = $(this).data('url')
      $.ajax({
          type: "patch",
          dataType: 'script',
          url: url
       });     
    });
    $('.editable').editable({
      mode: 'inline',
      showbuttons: false,
      onblur: 'ignore',
      error: function(response, newValue) { 
        var error_msgs = []
        $.each(response.responseJSON, function(key, value){ 
          error_msgs.push(value)
        })
        return error_msgs.join("; ");
      }
    })
  })

imentore-cms/app/views/imentore/admin/themes/_top.html.slim
- content_for :footer do
  javascript:
    $(document).ready(function(){
      $('ul.nav.nav-tabs li.active').attr('class','');
      var id = $('div.tab').attr('id');
      $('ul.nav.nav-tabs li#'+id).attr('class','active');
    })

ul.nav.nav-tabs
  / li#themes
  /   / a data-toggle="tab" href="#tab-1"  Credits
  /   = link_to t('imentore/theme', scope: [:activerecord, :models]), admin_theme_path(@theme), input_html:{data:{toggle:'tab'}}
  li#layouts
    = link_to t(:layouts), layouts_admin_theme_templates_path(@theme), input_html:{data:{toggle:'tab'}}
  li#templates
    = link_to t(:templates), admin_theme_templates_path(@theme), input_html:{data:{toggle:'tab'}}
  li#assets
    = link_to t(:assets), admin_theme_asset_folders_path(@theme), input_html:{data:{toggle:'tab'}}

imentore-cms/app/views/imentore/admin/themes/index.html.slim
.wrapper.wrapper-content.animated.fadeInRight
  .index
    = render "index"

imentore-cms/app/views/imentore/admin/themes/new.html.slim
/ = simple_form_for @theme, url: admin_themes_path do |f|
= simple_form_for @theme, url: admin_themes_path, :html => { :class => "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
  .wrapper.wrapper-content.animated.fadeInRight
    .row
      .col-lg-12
        .ibox.float-e-margins
          .ibox-title
            h5= t(:newo) + ' ' + t(:theme) 
            .ibox-tools
              a.collapse-link
                i.fa.fa-chevron-up
              a.dropdown-toggle data-toggle="dropdown" href="#" 
                i.fa.fa-wrench
              ul.dropdown-menu.dropdown-user
                / li
                /   a href="#"  Config option 1
                / li
                /   a href="#"  Config option 2
              a.close-link
                i.fa.fa-times
          .ibox-content
            = f.input :name
            .hr-line-dashed
            .form-group
              .col-sm-4.col-sm-offset-2
                = f.submit nil, :class => 'btn btn-primary'

imentore-cms/app/views/imentore/admin/themes/show.html.slim
- model_class = Imentore::Theme
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

.wrapper.wrapper-content.animated.fadeInRight
  .row  
    .col-lg-12
      .tabs-container
        =  render "imentore/admin/themes/top"
        / ul.nav.nav-tabs
        /   li.active
        /     a data-toggle="tab" href="#tab-1"  This is tab
        /   li
        /     a data-toggle="tab" href="#tab-2"  This is second tab
        / .tab-content
        /   .tab#themes.tab-pane.active
        /     .panel-body
        /       / = simple_form_for(@theme, url: admin_theme_path(@theme), html: {class: 'form-horizontal'}) do |f|
        /       = simple_form_for @theme, url: admin_theme_path(@theme), :html => { :class => "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
        /         = f.error_notification
        /         = f.input :active
        /         '
        /         = f.submit nil, :class => 'btn btn-primary'

imentore-cms/app/views/imentore/admin/themes/update.js.erb
$(".index").html("<%= escape_javascript(render("index")) %>");