imentore-ecommerce/config/routes.rb
Imentore::Core::Engine.routes.draw do

    resources :stores, only: [:new, :create]

    root to: "stores#show"

    namespace :admin do
      resource :store, only: [:edit, :update]
      get "store/settings/:group", to: "settings#edit",   as: "edit_settings"
      put "store/settings/:group", to: "settings#update", as: "update_settings"
      resources :domains, only: [:index, :create, :destroy] do
        resources :emails, only: [:index, :create, :update, :destroy], to: "domain_emails"
      end
      resources :feedbacks, only: [:uodate, :edit, :index, :destroy]
      resources :coupons
      resources :product_brands,  only: [:new, :create]
      resources :products do
        resources :options,  to: "product_options"
        resources :variants, to: 'product_variants' do
          resources :images, only: [:create, :destroy, :index], to: 'images'
        end
      end
      resources :payment_methods, path: "payment-methods"
      resources :delivery_methods,  except: [:show], path: "delivery-methods"
      resources :orders,  only: [:index, :edit, :destroy, :update] do
        get 'confirm_invoice', 'confirm_delivery', 'cancel', :on => :member
        put 'confirm_invoice', 'confirm_delivery', 'cancel', :on => :member
      end

      resources :categories, only: [:edit, :index, :update, :create, :destroy, :new]
    end

    resources :stores, only: [:show] do
      get "render_template/:template", action:"render_template", on: :collection
      resources :feedbacks, only: [:create, :new]
    end
    resources :order_assets, only: [:new, :create, :destroy, :index]
    resources :products,  only: [:index, :show]
    resource  :cart,      only: [:show, :create, :update, :destroy, :calculate_shipping] do
      get 'calculate_shipping', on: :member
    end

    get "checkouts",                   to: "checkouts#start"
    resources :checkouts, only: [:create] , path:'/:store_id/checkouts/:order_id' do
      # get '/', action: :new, controller: 'checkouts', on: :collection
      # get '/', action: :start, on: :collection, as: 'start'
      get '/address', action: :address, on: :collection, as: 'address'
      put '/address', action: :address, on: :collection, as: 'address_confirm'
      get '/shipping', action: :shipping, on: :collection, as: 'shipping'
      put '/shipping', action: :shipping, on: :collection, as: 'shipping_shipping'
      get '/payment', action: :payment, on: :collection, as: 'payment'
      put '/payment', action: :payment, on: :collection, as: 'confirm_payment'
      get '/complete', action: :complete, on: :collection, as: 'complete'
    end
    
    get "store/success",                             to: "stores#create_success"
    get "contact",                                   to: "stores#contact",       as: "store_contact"
    get "product/render_template/:template",         to: "products#render_template",        as: 'render_template_product'
    get "product/:handle",                           to: "products#handle",      as: 'product_handle'
    post "products/search",           to: "products#search",      as: 'products_search'
    get "products/result/:name",      to: "products#result",      as: 'products_result'
    get "notices/:handle",            to: "notices#show",         as: "notices"
    get "pages/:page",                to: "pages#show",           as: "pages"
    get "categories/*categories",     to: "categories#index",     as: "categories"
    get "coupon",                     to: "coupons#add_coupon",   as: "add_coupon"
    # get "checkout",                   to: "checkouts#new",                    as: "checkout"
    # get "checkout/address",       to: "checkouts#address",  via: "get",   as: "address_checkout"
    # match "checkout/address",       to: "checkouts#address",   as: "address",  via: [:get, :put]
    # get "checkout/:id/confirm",   to: "checkouts#confirm",  via: "get",   as: "confirm_checkout"
    # match "checkout/:id/confirm",   to: "checkouts#confirm",  as: "confirm_checkout", via:[:get, :put]
    # get "checkout/charge",        to: "checkouts#charge",   as: "charge_checkout"
    # get "checkout/:id/complete",  to: "checkouts#complete", as: "complete_checkout"
    get "return_mp/:invoice_id",  to: "checkouts#return_mp", as: 'return_mp'
    get "return_pd/:invoice_id",  to: "checkouts#return_pd", as: 'return_pd'
    get "return_pg/:invoice_id",  to: "checkouts#return_pg", as: 'return_pg'
    get "sync_pd/:invoice_id",    to: "checkouts#sync_pd",   as: 'sync_pd'
    get "sync_pg/:store_id",      to: "checkouts#sync_pg",   as: 'sync_pg'
    get "sync_mp/:store_id",      to: "checkouts#sync_mp",   as: 'sync_mp'
end

imentore-ecommerce/app/models/imentore/product.rb
module Imentore
  class Product < ActiveRecord::Base
    acts_as_paranoid

    before_destroy :destroy_disabled

    attr_accessor :product_brand_name

    has_many    :options,   class_name: "::Imentore::OptionType", dependent: :destroy
    has_many    :variants,  class_name: "::Imentore::ProductVariant", dependent: :destroy
    belongs_to  :store
    belongs_to  :product_brand

    has_many :categories_products, dependent: :destroy
    has_many :categories, :through => :categories_products, :source => :category
    has_many :feedbacks, as: :feedbackable, dependent: :destroy

    scope :active,         -> { where(active: true) }
    scope :featured,       -> { where(featured: true) }
    scope :product_search, -> (object){ where("name like ?", "%#{object}%") }

    validates :name, :handle, :store, presence: true
    validates :handle, uniqueness: { scope: :store_id }
    # validates :handle, format: { with: /^[-A-Za-z\d_]+$/ }

    accepts_nested_attributes_for :variants, allow_destroy: true

    def destroy_disabled
      update_column(:active, 0)
    end

    def handle
      return if read_attribute(:name).blank?
      if read_attribute(:handle).blank? 
        self.handle = name.to_underscore
        read_attribute(:handle)
      else 
        read_attribute(:handle)
      end
    end

    def handle=(param)
      write_attribute(:handle, param.to_underscore!)
    end


    def all_images
      imgs = []
      variants.each do |variant|
        imgs << variant.images.map {|image| image}
      end
      imgs.reject{|x| x.blank?}.flatten
    end

    def stock_available?
      variants.each do |v| 
        return true if v.quantity > 0 
      end
      return false
    end

  end
end

imentore-ecommerce/app/controllers/imentore/admin/products_controller.rb
module Imentore
  module Admin
    class ProductsController < BaseController
      inherit_resources
      # actions :index, :new, :create, :edit, :update
      respond_to :json, only: :update

      def index
        index! do |index|
          # index.html{@products = current_store.products.paginate(:page => params[:page]).order(sort_column + " " + sort_direction)}
          index.html{@products = current_store.products}
          index.json {render json: Imentore::ProductsDatatable.new(view_context, current_store)}
        end
      end

      def new
        @product = build_resource
        @product.variants.build
        new!
      end

      def edit
        @product_brand = current_store.product_brands.build
        edit!
      end

      def create
        create! do |success, failure|
          success.html do
            default_option = @product.options.create(name: t(:default), handle: t(:default).to_underscore)
            variant = @product.variants.first
            variant.options.create(option_type: default_option, value: t(:default))
            redirect_to admin_products_path
          end
          failure.html do
            render :new
          end
        end
      end

      def update
        @product = current_store.products.find_by_id(params[:id])
        @product.attributes = product_params
        update! do |success, failure|
          success.html do
            @product.product_brand = current_store.product_brands.find_by_name(params[:product][:product_brand_name])
            @product_brand = @product.product_brand
            @product.save
            flash[:success] = t(:product_updated)
            redirect_to edit_admin_product_path(@product)
          end
          success.json do
            @product.category_ids = []
            @product.category_ids = params[:product][:category_ids]
            render :edit
          end
          failure.html do
            @product.product_brand = current_store.product_brands.find_by_name(params[:product][:product_brand_name])
            @product_brand = @product.product_brand
            render :update
          end
        end
      end

      def destroy
        destroy! do 
          flash[:success] = "Removido com sucesso"
          admin_products_path
        end
      end


      protected

      def begin_of_association_chain
        current_store
      end

      def product_params
        params.require(:product).permit(:active, :featured, :handle, :product_brand_name, :name, :description, :description_preview,
                                        variants_attributes: [:price, :quantity, :weight])
                                            #.tap {|whitelisted| whitelisted[:category_ids] = params[:product][:category_ids] end
      end
      
    end
  end
end

imentore-ecommerce/app/controllers/imentore/products_controller.rb
module Imentore
  class ProductsController < BaseController
    respond_to :html, :js, :json
    include SqlTemplate::ResolverMethods

    def render_template
      product = current_store.products.active.find_by_handle(params[:handle])
      @product = ProductDrop.new(product)
      @variants = product.variants.map { |variant| ProductVariantDrop.new(variant) }
      @images = product.all_images.map { |image| ImageDrop.new(image)}
      if params[:template]
        template_liquid = render_to_controller(params[:template])
        respond_to do |format|
          format.html { render :inline => template_liquid }
          format.json do 
            render :json => {response: template_liquid}, status: 200
          end
        end
      end
    end

    def handle
      product = current_store.products.active.find_by_handle(params[:handle])
      @product = ProductDrop.new(product)
      respond_to do |format|
        if not product.nil? and not product.try(:variants).nil?
          @variants = product.variants.map { |variant| ProductVariantDrop.new(variant) }
          @images = product.all_images.map { |image| ImageDrop.new(image)}
          @content_for_footer = render_to_controller("imentore/products/show", :header_view)
          # @content_for_footer = render_to_string(template:(render_template_controller("imentore/products/show", :header_view)), layout:false)
          format.html { render :show }
        else
          format.html { render template: "_error_page", status: 404 }
        end
      end
    end

    def show
      product = current_store.products.active.find_by_handle(params[:handle])
      @product = ProductDrop.new(Imentore::Product.find_by_id(params[:id]))
      respond_to do |format|
        if not product.nil? and not product.try(:variants).nil?
          @variants = @product.variants.map { |variant| ProductVariantDrop.new(variant) }
          @images = @product.all_images.map { |image| ImageDrop.new(image)}
          format.html { }
          format.js 
        else
          format.html { render template: "_error_page", status: 404 }
        end
      end
    end

    def search
      if params[:name].present?
        redirect_to products_result_path(name: params[:name])
      else
        @products = []          
        render :result
      end
    end

    def result
      @product = Imentore::ProductSearchDrop.new(params[:name]) 
      @products_model = current_store.products.active.product_search(params[:name]).order(sort_column)
      @products = @products_model.map {|p| Imentore::ProductDrop.new(p)}
      @products ||= []          
    end

  end
end

imentore-ecommerce/app/views/imentore/admin/products/_top.html.slim
- content_for :footer do
  javascript:
    $(document).ready(function(){
      $('ul.nav.nav-tabs li.active').attr('class','');
      var id = $('div.tab').attr('id');
      $('ul.nav.nav-tabs li#'+id).attr('class','active');
    })

ul.nav.nav-tabs
  li#product
    = link_to(t(:product), edit_admin_product_path(@product))
  li#variants
    = link_to(t(:variants), admin_product_variants_path(@product))
  li#options
    = link_to(t(:options), admin_product_options_path(@product))

imentore-ecommerce/app/views/imentore/admin/products/edit.html.slim
- content_for :footer do
  css:
    ul.dynatree-container { 
      height: 300px;important! 
      overflow: scroll;important!
    }
  javascript:
    $(function(){
      $('.typeahead').typeahead()
      function updateCategories(cat_ids){
        var ids = (cat_ids == "" ? null : cat_ids)
        $.ajax({
          url: '#{{admin_product_path(@product)}}',
          type: 'put',
          data: {authenticity_token:"#{{form_authenticity_token}}", product:{category_ids:ids}},
          dataType: 'json',
          success: function(json) {
          }
        })
      }

      $("#tree3").dynatree({
        initAjax: {
          url: '#{{admin_categories_path}}',
          data: {
            product_id: '#{{@product.id}}',
          }
        },
        checkbox: true,
        selectMode: 2,
        //minExpandLevel:1,
        //autoCollapse:false,
        //activeVisible:true,
        onSelect: function(select, node) {
          // Get a list of all selected nodes, and convert to a key array:
          var selKeys = $.map(node.tree.getSelectedNodes(), function(node){
            return node.data.key;
          });
          $("#echoSelection3").text(selKeys.join(", "));

          // Get a list of all selected TOP nodes
          var selRootNodes = node.tree.getSelectedNodes(true);
          // ... and convert to a key array:
          var selRootKeys = $.map(selRootNodes, function(node){
            return node.data.key;
          });
          $("#echoSelectionRootKeys3").text(selRootKeys.join(", "));
          $("#echoSelectionRoots3").text(selRootNodes.join(", "));

          updateCategories(selKeys)
        },
        onDblClick: function(node, event) {
          node.toggleSelect();
        },
        onKeydown: function(node, event) {
          if( event.which == 32 ) {
            node.toggleSelect();
            return false;
          }
        },
        // The following options are only required, if we have more than one tree on one page:
        //  initId: "treeData",
        cookieId: "dynatree-Cb3",
        idPrefix: "dynatree-Cb3-"
      });
      $("#btnToggleSelect").click(function(){
        $("#tree2").dynatree("getRoot").visit(function(node){
          node.toggleSelect();

        });
        return false;
      });
      $("#btnDeselectAll").click(function(){
        $("#tree2").dynatree("getRoot").visit(function(node){
          node.select(false);
        });
        return false;
      });
      $("#btnSelectAll").click(function(){
        $("#tree2").dynatree("getRoot").visit(function(node){
          node.select(true);
        });
        return false;
      });
      <!-- Start_Exclude: This block is not part of the sample code -->
      $("#skinCombo")
      .val(0) // set state to prevent caching
      .change(function(){
        var href = "../src/"
          + $(this).val()
          + "/ui.dynatree.css"
          + "?reload="+ new Date().getTime();
        $("#skinSheet").attr("href", href);
      });
    });

- model_class = Imentore::Product
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    h2= t('edit', :default => t('helpers.links.edit'))
    ol.breadcrumb
      li
        = link_to model_class.model_name.human.pluralize.titleize, admin_products_path
      li.active
        strong
          = @product.name
  .col-lg-2


/ = render "imentore/admin/products/top"

.wrapper.wrapper-content.animated.fadeInRight
  .row  
    .col-lg-12
      .tabs-container
        =  render "imentore/admin/products/top"
        / ul.nav.nav-tabs
        /   li.active
        /     a data-toggle="tab" href="#tab-1"  This is tab
        /   li
        /     a data-toggle="tab" href="#tab-2"  This is second tab
        .tab-content
          .tab#product.tab-pane.active
            .panel-body
              = simple_form_for @product, url: [:admin, @product], :html => { :class => "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
                .row
                  .col-md-6
                    = f.error_notification
                    = f.input :active
                    = f.input :featured
                    = f.input :name
                    = f.input :handle
                    = f.input :description_preview, input_html: { :rows => 2, :class => 'textarea' }, :as => :text
                    = f.input :description, input_html: { :rows => 5, :class => 'textarea' }, :as => :text
                  .col-md-6
                    h4
                      = t(:categories)
                    #tree3
                .row
                  .col-md-12
                    legend= t(:brand)
                    = f.input :product_brand_name, input_html: {class: 'span5', 'data-provide'=>"typeahead", 'data-source'=>"#{brand_collection(current_store)}", value: f.object.try(:product_brand).try(:name), autocomplete:"off"}, placeholder: t(:product_brand_select) + '...'
                / .row
                /   .span10
                /     = link_to('#product-brand', class: :btn, 'data-toggle'=>'modal') do
                /       i.icon-black.icon-plus
                /       '
                /       = t(:product_brand_new)
                .hr-line-dashed
                .row 
                  .col-md-12
                    .form-group
                      .col-sm-4.col-sm-offset-0
                        = f.submit(:class => "btn btn-primary")

#product-brand.modal.hide.fade.in
  = render file: 'imentore/admin/product_brands/new', product: @product

.hide

imentore-ecommerce/app/views/imentore/admin/products/index.html.slim
- content_for :header do
  = javascript_include_tag('admin/datatable.js')
/ - content_for :breadcrumb do
/   == breadcrumb([{ t(:home) => admin_dashboard_path }, { 'Configuration' => url_for(:controller => :themes) }, { 'Themes' => url_for(:controller => :themes) }])

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          h5= t(:product_index)
          .ibox-tools
            a.collapse-link
              i.fa.fa-chevron-up
            a.dropdown-toggle data-toggle="dropdown" href="#" 
              i.fa.fa-wrench
            ul.dropdown-menu.dropdown-user
              / li
              /   a href="#"  Config option 1
              / li
              /   a href="#"  Config option 2
            a.close-link
              i.fa.fa-times
        .ibox-content
          table.table.table-striped.table-bordered.table-hover.dataTables-example#datatable[data-source="#{admin_products_url(format: 'json')}"]
            thead
              tr
                th.w-5= t(:id)
                th.w-10= t(:status)
                th.w-15= t(:created_at)
                th.input-medium= t(:name)
                th.input-large= t(:action)
          .row 
            .hr-line-dashed
            .form-group
              .col-sm-4.col-sm-offset-0
                = link_to(new_admin_product_path, :class=>'btn btn-primary') do
                  i.icon-white.icon-plus
                  '
                  = t(:product_new)

/ .wrapper.wrapper-content.animated.fadeInRight.ecommerce
/   .ibox-content.m-b-sm.border-bottom
/   .row
/     .col-lg-12
/       .ibox
/         .ibox-content
  / tfoot[style='display:table-header-group']
  /   tr
  /     th id
  /     th status
  /     th created_at
  /     th[colspan=2] name
  /     / th handle
  / tbody
  /   - @products.each do |product|
  /     tr
  /       td= product.id
  /       td= button_status(product.active, edit_admin_product_path(product))
  /       td= l(time_zone(product.created_at), format: :short2)
  /       td= link_to(product.name, edit_admin_product_path(product))
  /       / td= product.handle
  /       td
  /         = link_to(edit_admin_product_path(product), class: 'btn btn-small') do
  /           i.icon-black.icon-edit
  /           '
  /           = t(:edit)
  /         '
  /         = link_to(admin_product_variants_path(product), :class=>"btn btn-small") do
  /           i.icon-black.icon-share
  /           '
  /           = t(:variants)
  /         '
  /         = link_to(admin_product_options_path(product), :class=>"btn btn-small") do
  /           i.icon-black.icon-plus
  /           '
  /           = t(:options)            
  / = will_paginate @products, :renderer => BootstrapPagination::Rails

imentore-ecommerce/app/views/imentore/admin/products/new.html.slim
/ = simple_form_for(, :html => {:class => 'form-horizontal'}) do |f|
= simple_form_for @product, url: [:admin, @product], :html => { :class => "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
  .wrapper.wrapper-content.animated.fadeInRight
    .row
      .col-lg-12
        .ibox.float-e-margins
          .ibox-title
            h5
              = t(:newo) + " " + t(:product)
              / small Simple login form example
          .ibox-content
            = f.error_notification
            = f.input :name
            - unless f.error_notification.blank?
              = f.input :handle
            = f.input :description
            = f.simple_fields_for(:variants) do |v|
              = v.input :price, as: :string
              = v.input :quantity, as: :integer
              = v.input :weight, as: :string
            .form-actions
              = f.submit(:class => "btn btn-primary")